### ISSUE TITLE
Ability to access population for different areas

### ISSUE THREAD

**Issue by 40621915** [CallumG04/SEM_CW_GROUPH#8]
As a member of the organisation
I want the ability to access countries populations
So that I can see the top N for population in that area

**Comment by OliverWalker00** [comment]
Goal in Context
As a member of the organisation
I want the ability to access countries populations
So that I can see the top N for population in that area

Scope
Organisation

Level
Primary task.

Preconditions
we have the relevant data for each countries population ready to query in the database

Success End Condition
A report is available for the organisation to see the population 

Failed End Condition
No report is produced.

Primary Actor
member of organisation

Trigger
A request for population is sent by a member of the organisation 

MAIN SUCCESS SCENARIO
organisation member request population information for a given "N"  number of countries.
organisation member extracts population information of "N" amount of countries produced from report.

SUB-VARIATIONS
None.

SCHEDULE
DUE DATE: Release 1.0
